import CoreML
import Vision
import UIKit

/// Manages the Core ML face-embedding model and performs nearest-neighbour
/// matching against enrolled contacts.
final class FaceRecognitionService {

    /// Recognition result when a match exceeds the similarity threshold.
    struct MatchResult {
        let contactID: String
        let contactName: String
        let similarity: Float
        let boundingBox: CGRect
    }

    /// Cosine-similarity threshold. Embeddings above this are a match.
    var similarityThreshold: Float = 0.65

    private var model: VNCoreMLModel?

    // MARK: - Model loading

    /// Load the Core ML embedding model bundled in the app.
    func loadModel() {
        do {
            let config = MLModelConfiguration()
            config.computeUnits = .all // prefer Neural Engine

            // The model class is generated by Xcode from FaceEmbedding.mlpackage
            let coreMLModel = try FaceEmbedding(configuration: config).model
            model = try VNCoreMLModel(for: coreMLModel)
        } catch {
            print("[FaceRecognition] Failed to load model: \(error)")
        }
    }

    // MARK: - Embedding

    /// Compute a 128-d embedding for a cropped face image.
    func embedding(for faceImage: CGImage) -> [Float]? {
        guard let model else { return nil }

        var result: [Float]?
        let request = VNCoreMLRequest(model: model) { req, _ in
            guard let observations = req.results as? [VNCoreMLFeatureValueObservation],
                  let multiArray = observations.first?.featureValue.multiArrayValue
            else { return }

            let count = multiArray.count
            var vec = [Float](repeating: 0, count: count)
            let ptr = multiArray.dataPointer.bindMemory(to: Float.self, capacity: count)
            for i in 0..<count {
                vec[i] = ptr[i]
            }
            // L2-normalise
            let norm = sqrt(vec.reduce(0) { $0 + $1 * $1 })
            if norm > 0 {
                vec = vec.map { $0 / norm }
            }
            result = vec
        }
        request.imageCropAndScaleOption = .scaleFill

        let handler = VNImageRequestHandler(cgImage: faceImage, options: [:])
        do {
            try handler.perform([request])
        } catch {
            print("[FaceRecognition] Embedding failed: \(error)")
        }
        return result
    }

    // MARK: - Matching

    /// Match a detected face against all enrolled contacts.
    func match(
        face: DetectedFace,
        against contacts: [Contact]
    ) -> MatchResult? {
        guard let queryEmbedding = embedding(for: face.croppedFace) else {
            return nil
        }

        var bestMatch: MatchResult?
        var bestSimilarity: Float = similarityThreshold

        for contact in contacts {
            for stored in contact.embeddings {
                let sim = cosineSimilarity(queryEmbedding, stored)
                if sim > bestSimilarity {
                    bestSimilarity = sim
                    bestMatch = MatchResult(
                        contactID: contact.id,
                        contactName: contact.name,
                        similarity: sim,
                        boundingBox: face.boundingBox
                    )
                }
            }
        }
        return bestMatch
    }

    // MARK: - Helpers

    private func cosineSimilarity(_ a: [Float], _ b: [Float]) -> Float {
        guard a.count == b.count else { return 0 }
        var dot: Float = 0
        var normA: Float = 0
        var normB: Float = 0
        for i in 0..<a.count {
            dot += a[i] * b[i]
            normA += a[i] * a[i]
            normB += b[i] * b[i]
        }
        let denom = sqrt(normA) * sqrt(normB)
        return denom > 0 ? dot / denom : 0
    }
}
